### ISSUE TITLE
OpenInv not working using Java 11

### ISSUE THREAD

**Issue by TRose2000** [lishid/OpenInv#100] opened 2019-03-29 16:25 UTC
When I use /open <name> I get errors and it shows a empty inventory since the plugin wasnt made for java 11, is it possible to quickly add this

**Comment by RoboMWM** [comment] 2019-03-29 16:35
Duplicate of #93

**Comment by Jikoo** [comment] 2019-03-29 21:22
Duplicate of #93 as Robo said

**Closed by Jikoo** 2019-03-29 21:22 UTC
