### ISSUE TITLE
Errors when i do /oi and /oe

### ISSUE THREAD

**Issue by bandithello1** [lishid/OpenInv#178] opened 2021-02-18 07:13 UTC
Im running paper 1.12.2 and running openinv and when ever i do /oe <player> or /oi <player> it gives me 

[08:07:14 WARN]: java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_12_R1.NonNullList field net.minecraft.server.v1_12_R1.PlayerInventory.items to net.minecraft.server.v1_12_R1.NonNullList
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[08:07:14 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:780)
[08:07:14 WARN]:        at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.setItemArrays(SpecialPlayerInventory.java:165)
[08:07:14 WARN]:        at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:44)
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:07:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:07:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[08:07:14 WARN]:        at com.lishid.openinv.util.InternalAccessor.createObject(InternalAccessor.java:103)
[08:07:14 WARN]:        at com.lishid.openinv.util.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:210)
[08:07:14 WARN]:        at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:327)
[08:07:14 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
[08:07:14 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
[08:07:14 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
[08:07:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[08:07:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[08:07:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[08:07:14 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[08:07:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[08:07:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[08:07:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
these errors please respond asap

**Comment by Jikoo** [comment] 2021-02-18 14:45
If you want to use an outdated server, you must use a matching outdated Java version. Either update your server to a modern version or downgrade to Java 8.

**Comment by Jikoo** [comment] 2021-02-18 14:46
Duplicate of #173

**Closed by Jikoo** 2021-02-18 14:45 UTC
