### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Uhevela** [lishid/OpenInv#95] opened 2019-01-12 23:21 UTC
Hello, I need some help.
I have a long error message that appears in my console. Here it is:

[22:05:09 ERROR]: Could not pass event PlayerInteractEvent to OpenInv v3.3.6
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.VoxelShape.a()Lnet/minecraft/server/v1_13_R2/AxisAlignedBB;
        at com.lishid.openinv.internal.v1_13_R2.AnySilentContainer.isBlockedShulkerBox(AnySilentContainer.java:134) ~[?:?]
        at com.lishid.openinv.internal.v1_13_R2.AnySilentContainer.isAnyContainerNeeded(AnySilentContainer.java:86) ~[?:?]
        at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:66) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-498]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:474) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1355) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-498]
        at
net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191][22:05:09 ERROR]: Could not pass event PlayerInteractEvent to OpenInv v3.3.6
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.VoxelShape.a()Lnet/minecraft/server/v1_13_R2/AxisAlignedBB;
        at com.lishid.openinv.internal.v1_13_R2.AnySilentContainer.isBlockedShulkerBox(AnySilentContainer.java:134) ~[?:?]
        at com.lishid.openinv.internal.v1_13_R2.AnySilentContainer.isAnyContainerNeeded(AnySilentContainer.java:86) ~[?:?]
        at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:66) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-498]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-498]
        at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:474) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1355) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:748)
[?:1.8.0_191]

Thank you for your help:)

**Comment by Jikoo** [comment] 2019-01-16 00:36
Duplicate of #94

**Closed by Jikoo** 2019-01-16 00:36 UTC
