### ISSUE TITLE
/openinv /openender don't work

### ISSUE THREAD

**Issue by OllieJW** [lishid/OpenInv#181] opened 2021-02-22 22:49 UTC
Description:
Im using spigot 1.16.5 and suddenly all of the other commands like /silentcontainer and /anychest work but I cant see users inventories/ender chests. This plugin was working before and now it has randomly stopped.
Plugins:
![image](https://user-images.githubusercontent.com/71931263/108780257-0ec47b80-7560-11eb-937b-3914708d1394.png)
Error:
Task #1172050 for OpenInv v4.1.5 generated an exception

**Comment by Jikoo** [comment] 2021-02-22 23:01
Duplicate of #179

**Closed by Jikoo** 2021-02-22 23:01 UTC
