### ISSUE TITLE
Console error at start

### ISSUE THREAD

**Issue by VirgilFabre** [lishid/OpenInv#111] opened 2019-08-16 17:17 UTC
13:16:33 [WARNING] Plugin OpenInv v4.0.3 does not specify an api-version.

Easy to fix

**Comment by Jikoo** [comment] 2019-08-16 19:10
OpenInv supports 1.8, 1.13, and 1.14 currently. Spigot does not allow specifying older API versions, and will not load plugins which do specify them.

**Comment by VirgilFabre** [comment] 2019-08-16 19:11
Then add api-version 1.8 so it knows to get the 1.8 API at minimum
Just to remove warning message

**Comment by VirgilFabre** [comment] 2019-08-16 19:12
Oh ok Just understood your message, welp.... rip spigot, pretty sure there s a way tho

**Comment by Jikoo** [comment] 2019-08-16 21:19
Yeah, the only way is to specify api-version 1.13 or higher. Technically that would probably be fine, but since a) it's not really a problem and b) it's not actually true - the plugin is [built against 1.8.8](https://github.com/lishid/OpenInv/blob/master/plugin/pom.xml#L39), I don't really want to include it.

I suppose it's worth reconsidering. This isn't an isolated request, it's a duplicate of #102. Would appreciate community feedback.

**Comment by Jikoo** [comment] 2019-08-16 21:25
Actually, after more thought, I am likely to include api-version 1.13. The last time it came up I was opposed to it, but OpenInv's nature is that it is somewhat version-specific and volatile.
There is likely (very slight) additional unnecessary processing associated with OpenInv for legacy support it doesn't actually require. In addition, not including the API version would cause it to be a bit more annoying to do pretty printing for things like #35 if I ever get around to it.

**Comment by VirgilFabre** [comment] 2019-08-16 21:37
Would be logic, cause api-version start from 1.13 so just adding the lowest api-version supported would fix the warning I think

**Closed** 2019-09-29 23:43 UTC
