### ISSUE TITLE
Don´t open

### ISSUE THREAD

**Issue by FuntyGithub** [lishid/OpenInv#184] opened 2021-03-08 12:31 UTC
If i run a command from this plugin it show this error in the consol und nothing happens

`[13:29:26 WARN]: [OpenInv] Task #3004 for OpenInv v4.1.5 generated an exception
java.lang.AbstractMethodError: Receiver class com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$2 does not define or inherit an implementation of the resolved method 'abstract net.kyori.adventure.text.Component title()' of abstract class org.bukkit.inventory.InventoryView.
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftContainer.<init>(CraftContainer.java:54) ~[patched_1.16.5.jar:git-Paper-480]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$3.<init>(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager.openInventory(PlayerDataManager.java:237) ~[?:?]
        at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:265) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:173) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34) ~[?:?]
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-480]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-480]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-480]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-480]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-480]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-480]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-480]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Jikoo** [comment] 2021-03-08 12:34
Duplicate of #179

**Comment by Jikoo** [comment] 2021-03-08 12:35
Update your server.

**Closed by Jikoo** 2021-03-08 12:34 UTC
